### ISSUE TITLE
If set minWidth or minHeight, Cannot resize.

### ISSUE THREAD

**Issue by argxentakato** [bokuweb/react-rnd#739]
### Overview of the problem

I'm using react-rnd **version** 10.2.2
      
My **browser** is: Chromium
   
I am sure this issue is **not a duplicate**? Yes.
   
### Reproduced project

https://codesandbox.io/s/young-microservice-md19b

### Description
If I set minWidth or minHeight to prevent Rnd from being smaller than your children divs (whether it's a fixed value like "300px" or a keyword like "fit-content") I'll not be able to resize it completely.

### Steps to Reproduce
1. Just put on miniWidth or minHeight

### Expected behaviour
Can resize it to a size not less than minWidth (minHeight).

### Actual behaviour
It's as if it's frozen and won't move.

**Comment by akshaybosamiya** [comment]
I'm also facing the same issue. 

@bokuweb, please let us know if there is any update on this. 

Thanks a lot.

**Comment by bokuweb** [comment]
@akshaybosamiya @silverscat-3 fixed by v10.2.3

**Comment by fatinWasta** [comment]
+1
Still persist for me. the current version is `10.3.4` . 
Can anyone please look into this?

**Comment by ImLunaHey** [comment]
same issue here with `10.4.1`

**Comment by bokuweb** [comment]
sorry I'll do some investigation.
